# Generated by Django 6.1.1 on 2026-09-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number',
            field=models.IntegerField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
