# Generated by Django 6.1.1 on 2026-09-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
